# Rectangle Deconvolution of brain organoid data (BrainO)

This notebook demonstrates cell-type deconvolution using Rectangle.

In [1]:
import rectanglepy as rp
import pandas as pd
from anndata import AnnData, read_h5ad
from scipy.sparse import csr_matrix

## Load bulk data

In [2]:
bulks = pd.read_csv("braino_clean.zip", index_col=0).T
bulks[['TUBB2B', 'TUBB', 'SOX11', 'ACTG1']].head()

                                 TUBB2B         TUBB        SOX11        ACTG1
1-H1-dorsal-day013-016      1753.996448  2748.174462  2269.587527  2629.761200
1-H9-dorsal-day013-016      1069.900143  2543.774380  2865.691238  2278.666381
1-ROZH_5-dorsal-day013-016  1753.396508  2283.882712  2328.555235  2959.554615
1-XUJA_2-dorsal-day013-016  2673.506501  2632.793204  1838.883913  5883.071411
1-176-dorsal-day013-016     2294.623149  2679.214916  2226.754013  2853.735550

## Load sc data

In [3]:
sc_adata = read_h5ad("braino_sc.h5ad")
sc_adata[:, ['TUBB2B', 'TUBB', 'SOX11', 'ACTG1']].to_df().head()

                                  TUBB2B  TUBB  SOX11  ACTG1
111-H1-D-ORG1_AAACCCATCCTGGTCT-1     0.0   0.0    1.0    5.0
111-H1-D-ORG1_AAACGCTCATTGAAAG-1     1.0   0.0    1.0   18.0
111-H1-D-ORG1_AAAGGATTCATAGAGA-1     2.0   0.0    0.0   17.0
111-H1-D-ORG1_AAAGGGCCATCTGTTT-1     0.0   0.0    0.0   10.0
111-H1-D-ORG1_AAAGGGCGTGTCTAAC-1     1.0   0.0    0.0    3.0

In [7]:
sc_adata.obs.value_counts().index

MultiIndex([('ventral forebrain prog.',),
            (      'ventral forebrain',),
            (       'dorsal forebrain',),
            (                 'muscle',),
            ( 'dorsal forebrain prog.',),
            (                'stromal',),
            (              'hindbrain',),
            (                    'eye',),
            (        'hindbrain prog.',),
            (          'midbrain-like',),
            (               'striatum',),
            (      'diencephalon lin.',),
            (         'midbrain prog.',),
            (                  'oligo',),
            (         'choroid plexus',)],
           names=['cell_type'])

## Save sc data in sparse format

In [9]:
# sc_adata.X = csr_matrix(sc_adata.X)

## Run Rectangle deconvolution

In [6]:
estimations, signature_result = rp.rectangle(sc_adata, bulks)

2026-05-10 14:08:17.978 | INFO     | rectanglepy.pp.create_signature:build_rectangle_signatures:327 - Using 17048 common genes between bulks and single-cell data
2026-05-10 14:09:23.292 | INFO     | rectanglepy.pp.create_signature:_de_analysis:200 - Starting DE analysis
/Users/berni/PycharmProjects/rectangle_paper/.venv/lib/python3.12/site-packages/rectanglepy/pp/create_signature.py:181: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  bootstrapped_signature[f"{celltype}_{i}"] = list(summed_rows)
/Users/berni/PycharmProjects/rectangle_paper/.venv/lib/python3.12/site-packages/rectanglepy/pp/create_signature.py:181: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  bootstrapped_signature[f"{celltype}_{i}"] = list(summed_rows)
/Users/berni/PycharmProjects/rectangle_paper/.venv/lib/python3.12/site-packages/rectanglepy/pp/create_signature.py:181: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  bootstrapped_signature[f"{celltype}_{i}"] = list(summed_rows)
/Users/berni/PycharmProjects/rectangle_paper/.venv/lib/python3.12/site-packages/rectanglepy/pp/create_signature.py:181: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  bootstrapped_signature[f"{celltype}_{i}"] = list(summed_rows)
/Users/berni/PycharmProjects/rectangle_paper/.venv/lib/python3.12/site-packages/rectanglepy/pp/create_signature.py:181: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  bootstrapped_signature[f"{celltype}_{i}"] = list(summed_rows)
2026-05-10 14:09:29.253 | INFO     | rectanglepy.pp.create_signature:_run_deseq2:148 - Running DE analysis for choroid plexus
2026-05-10 14:09:33.003 | INFO     | rectanglepy.pp.create_signature:_run_deseq2:148 - Running DE analysis for diencephalon lin.
2026-05-10 14:09:35.510 | INFO     | rectanglepy.pp.create_signature:_run_deseq2:148 - Running DE analysis for dorsal forebrain
2026-05-10 14:09:38.082 | INFO     | rectanglepy.pp.create_signature:_run_deseq2:148 - Running DE analysis for dorsal forebrain prog.
2026-05-10 14:09:40.365 | INFO     | rectanglepy.pp.create_signature:_run_deseq2:148 - Running DE analysis for eye
2026-05-10 14:09:42.827 | INFO     | rectanglepy.pp.create_signature:_run_deseq2:148 - Running DE analysis for hindbrain
2026-05-10 14:09:44.690 | INFO     | rectanglepy.pp.create_signature:_run_deseq2:148 - Running DE analysis for hindbrain prog.
2026-05-10 14:09:47.222 | INFO     | rectanglepy.pp.create_signature:_run_deseq2:148 - Running DE analysis for midbrain prog.
2026-05-10 14:09:49.035 | INFO     | rectanglepy.pp.create_signature:_run_deseq2:148 - Running DE analysis for midbrain-like
2026-05-10 14:09:50.470 | INFO     | rectanglepy.pp.create_signature:_run_deseq2:148 - Running DE analysis for muscle
2026-05-10 14:09:52.425 | INFO     | rectanglepy.pp.create_signature:_run_deseq2:148 - Running DE analysis for oligo
2026-05-10 14:09:54.360 | INFO     | rectanglepy.pp.create_signature:_run_deseq2:148 - Running DE analysis for striatum
2026-05-10 14:09:57.308 | INFO     | rectanglepy.pp.create_signature:_run_deseq2:148 - Running DE analysis for stromal
2026-05-10 14:09:59.752 | INFO     | rectanglepy.pp.create_signature:_run_deseq2:148 - Running DE analysis for ventral forebrain
2026-05-10 14:10:02.693 | INFO     | rectanglepy.pp.create_signature:_run_deseq2:148 - Running DE analysis for ventral forebrain prog.
2026-05-10 14:10:03.311 | INFO     | rectanglepy.pp.create_signature:_de_analysis:205 - Optimizing cutoff parameters p and lfc
2026-05-10 14:10:03.311 | INFO     | rectanglepy.pp.create_signature:_optimize_parameters:408 - generating pseudo bulks
2026-05-10 14:10:05.854 | INFO     | rectanglepy.pp.create_signature:_get_marker_genes:225 - Optimal condition number: 22
2026-05-10 14:10:06.109 | INFO     | rectanglepy.pp.create_signature:_optimize_parameters:416 - RMSE:0.036787103877037715, Pearson R:-0.0634517299486136 for p=0.05, lfc=1.6

Polishing not needed - no active set detected at optimal point
Polishing not needed - no active set detected at optimal point
Polishing not needed - no active set detected at optimal point
Polishing not needed - no active set detected at optimal point

2026-05-10 14:10:06.347 | INFO     | rectanglepy.pp.create_signature:_get_marker_genes:225 - Optimal condition number: 21
2026-05-10 14:10:06.561 | INFO     | rectanglepy.pp.create_signature:_optimize_parameters:416 - RMSE:0.03789287036534294, Pearson R:-0.07306542375218628 for p=0.05, lfc=1.7

Polishing not needed - no active set detected at optimal point
Polishing not needed - no active set detected at optimal point
Polishing not needed - no active set detected at optimal point
Polishing not needed - no active set detected at optimal point
Polishing not needed - no active set detected at optimal point

2026-05-10 14:10:06.704 | INFO     | rectanglepy.pp.create_signature:_get_marker_genes:225 - Optimal condition number: 21

Polishing not needed - no active set detected at optimal point
Polishing not needed - no active set detected at optimal point
Polishing not needed - no active set detected at optimal point

2026-05-10 14:10:06.976 | INFO     | rectanglepy.pp.create_signature:_optimize_parameters:416 - RMSE:0.03809094216083892, Pearson R:-0.07262133215215776 for p=0.05, lfc=1.8
2026-05-10 14:10:07.106 | INFO     | rectanglepy.pp.create_signature:_get_marker_genes:225 - Optimal condition number: 22

Polishing not needed - no active set detected at optimal point
Polishing not needed - no active set detected at optimal point

2026-05-10 14:10:07.337 | INFO     | rectanglepy.pp.create_signature:_optimize_parameters:416 - RMSE:0.03887180412410708, Pearson R:-0.07175868711243849 for p=0.05, lfc=1.9

Polishing not needed - no active set detected at optimal point
Polishing not needed - no active set detected at optimal point
Polishing not needed - no active set detected at optimal point
Polishing not needed - no active set detected at optimal point
Polishing not needed - no active set detected at optimal point

2026-05-10 14:10:07.464 | INFO     | rectanglepy.pp.create_signature:_get_marker_genes:225 - Optimal condition number: 21
2026-05-10 14:10:07.672 | INFO     | rectanglepy.pp.create_signature:_optimize_parameters:416 - RMSE:0.03989598071383112, Pearson R:-0.061022090961476934 for p=0.05, lfc=2.0

Polishing not needed - no active set detected at optimal point
Polishing not needed - no active set detected at optimal point
Polishing not needed - no active set detected at optimal point

2026-05-10 14:10:07.927 | INFO     | rectanglepy.pp.create_signature:_get_marker_genes:225 - Optimal condition number: 22
2026-05-10 14:10:08.185 | INFO     | rectanglepy.pp.create_signature:_optimize_parameters:416 - RMSE:0.04089394752380853, Pearson R:-0.059006330424168765 for p=0.05, lfc=2.1

Polishing not needed - no active set detected at optimal point
Polishing not needed - no active set detected at optimal point
Polishing not needed - no active set detected at optimal point

2026-05-10 14:10:08.291 | INFO     | rectanglepy.pp.create_signature:_get_marker_genes:225 - Optimal condition number: 22

Polishing not needed - no active set detected at optimal point
Polishing not needed - no active set detected at optimal point
Polishing not needed - no active set detected at optimal point

2026-05-10 14:10:08.600 | INFO     | rectanglepy.pp.create_signature:_optimize_parameters:416 - RMSE:0.04158527330447769, Pearson R:-0.05984830686523751 for p=0.05, lfc=2.2
2026-05-10 14:10:08.602 | INFO     | rectanglepy.pp.create_signature:_de_analysis:208 - Optimization done
 Best cutoffs  p: 0.05 and lfc: 2.1
2026-05-10 14:10:08.659 | INFO     | rectanglepy.pp.create_signature:_get_marker_genes:225 - Optimal condition number: 22
2026-05-10 14:10:08.687 | INFO     | rectanglepy.pp.create_signature:build_rectangle_signatures:348 - Starting rectangle cluster analysis
2026-05-10 14:10:08.765 | INFO     | rectanglepy.pp.create_signature:_create_clustered_data:266 - Starting clustered analysis
2026-05-10 14:10:19.849 | INFO     | rectanglepy.pp.create_signature:_de_analysis:200 - Starting DE analysis
2026-05-10 14:10:28.083 | INFO     | rectanglepy.pp.create_signature:_run_deseq2:148 - Running DE analysis for 10
2026-05-10 14:10:31.548 | INFO     | rectanglepy.pp.create_signature:_run_deseq2:148 - Running DE analysis for 5
2026-05-10 14:10:34.295 | INFO     | rectanglepy.pp.create_signature:_run_deseq2:148 - Running DE analysis for 9
2026-05-10 14:10:35.085 | INFO     | rectanglepy.pp.create_signature:_run_deseq2:148 - Running DE analysis for choroid plexus
2026-05-10 14:10:36.421 | INFO     | rectanglepy.pp.create_signature:_run_deseq2:148 - Running DE analysis for dorsal forebrain
2026-05-10 14:10:37.692 | INFO     | rectanglepy.pp.create_signature:_run_deseq2:148 - Running DE analysis for dorsal forebrain prog.
2026-05-10 14:10:38.537 | INFO     | rectanglepy.pp.create_signature:_run_deseq2:148 - Running DE analysis for eye
2026-05-10 14:10:39.267 | INFO     | rectanglepy.pp.create_signature:_run_deseq2:148 - Running DE analysis for hindbrain prog.
2026-05-10 14:10:40.517 | INFO     | rectanglepy.pp.create_signature:_run_deseq2:148 - Running DE analysis for muscle
2026-05-10 14:10:41.246 | INFO     | rectanglepy.pp.create_signature:_run_deseq2:148 - Running DE analysis for oligo
2026-05-10 14:10:42.493 | INFO     | rectanglepy.pp.create_signature:_run_deseq2:148 - Running DE analysis for stromal
2026-05-10 14:10:43.152 | INFO     | rectanglepy.pp.create_signature:_get_marker_genes:225 - Optimal condition number: 20
2026-05-10 14:10:44.128 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 4
2026-05-10 14:10:44.128 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 5
2026-05-10 14:10:44.128 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 6
2026-05-10 14:10:44.128 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 2
2026-05-10 14:10:44.129 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 7
2026-05-10 14:10:44.130 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 3
2026-05-10 14:10:44.130 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 0
2026-05-10 14:10:44.130 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 1
2026-05-10 14:10:47.756 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 7
2026-05-10 14:10:47.783 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 8
2026-05-10 14:10:48.015 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 6
2026-05-10 14:10:48.041 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 5
2026-05-10 14:10:48.048 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 9
2026-05-10 14:10:48.052 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 1
2026-05-10 14:10:48.061 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 10
2026-05-10 14:10:48.084 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 11
2026-05-10 14:10:48.492 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 2
2026-05-10 14:10:48.518 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 12
2026-05-10 14:10:49.694 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 4
2026-05-10 14:10:49.727 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 13
2026-05-10 14:10:50.077 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 0
2026-05-10 14:10:50.102 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 14
2026-05-10 14:10:50.690 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 3
2026-05-10 14:10:50.727 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 15
2026-05-10 14:10:51.526 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 9
2026-05-10 14:10:51.542 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 16
2026-05-10 14:10:51.749 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 8
2026-05-10 14:10:51.766 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 17
2026-05-10 14:10:52.387 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 11
2026-05-10 14:10:52.426 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 18
2026-05-10 14:10:52.762 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 10
2026-05-10 14:10:52.790 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 19
2026-05-10 14:10:52.873 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 12
2026-05-10 14:10:52.902 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 20

Polishing not needed - no active set detected at optimal point
Polishing not needed - no active set detected at optimal point
Polishing not needed - no active set detected at optimal point
Polishing not needed - no active set detected at optimal point

2026-05-10 14:10:55.349 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 16
2026-05-10 14:10:55.375 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 21
2026-05-10 14:10:55.443 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 17
2026-05-10 14:10:55.466 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 22
2026-05-10 14:10:55.924 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 14
2026-05-10 14:10:55.962 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 23
2026-05-10 14:10:56.591 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 15
2026-05-10 14:10:56.595 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 13
2026-05-10 14:10:56.639 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 24
2026-05-10 14:10:56.641 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 25
2026-05-10 14:10:56.706 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 18
2026-05-10 14:10:56.740 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 26
2026-05-10 14:10:56.942 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 20
2026-05-10 14:10:56.971 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 27
2026-05-10 14:10:57.214 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 19
2026-05-10 14:10:57.238 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 28
2026-05-10 14:10:59.652 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 22
2026-05-10 14:10:59.669 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 29
2026-05-10 14:10:59.881 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 21
2026-05-10 14:10:59.906 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 30
2026-05-10 14:11:01.218 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 28
2026-05-10 14:11:01.230 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 27
2026-05-10 14:11:01.242 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 31
2026-05-10 14:11:01.245 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 32
2026-05-10 14:11:01.322 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 26
2026-05-10 14:11:01.348 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 33
2026-05-10 14:11:02.250 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 25
2026-05-10 14:11:02.268 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 34
2026-05-10 14:11:02.290 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 23
2026-05-10 14:11:02.330 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 35
2026-05-10 14:11:03.000 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 24
2026-05-10 14:11:03.022 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 36
2026-05-10 14:11:03.943 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 29
2026-05-10 14:11:03.968 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 37
2026-05-10 14:11:04.287 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 30
2026-05-10 14:11:04.316 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 38
2026-05-10 14:11:05.204 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 31
2026-05-10 14:11:05.233 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 39
2026-05-10 14:11:05.240 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 33
2026-05-10 14:11:05.259 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 40
2026-05-10 14:11:05.400 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 32
2026-05-10 14:11:05.413 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 41
2026-05-10 14:11:08.237 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 35
2026-05-10 14:11:08.266 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 42
2026-05-10 14:11:08.282 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 37
2026-05-10 14:11:08.314 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 43
2026-05-10 14:11:08.338 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 38
2026-05-10 14:11:08.353 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 44
2026-05-10 14:11:08.663 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 34
2026-05-10 14:11:08.700 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 45
2026-05-10 14:11:08.794 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 36
2026-05-10 14:11:08.817 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 46
2026-05-10 14:11:09.162 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 39
2026-05-10 14:11:09.176 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 47
2026-05-10 14:11:09.214 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 41
2026-05-10 14:11:09.239 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 48
2026-05-10 14:11:09.580 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 40
2026-05-10 14:11:09.629 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 49
2026-05-10 14:11:12.404 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 43
2026-05-10 14:11:12.447 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 50
2026-05-10 14:11:12.639 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 44
2026-05-10 14:11:12.660 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 51
2026-05-10 14:11:13.562 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 47
2026-05-10 14:11:13.584 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 52
2026-05-10 14:11:14.371 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 48
2026-05-10 14:11:14.390 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 53
2026-05-10 14:11:14.574 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 49
2026-05-10 14:11:14.592 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 54
2026-05-10 14:11:16.396 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 45
2026-05-10 14:11:16.412 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 42
2026-05-10 14:11:16.435 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 55
2026-05-10 14:11:16.489 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 56
2026-05-10 14:11:17.091 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 50
2026-05-10 14:11:17.126 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 57
2026-05-10 14:11:17.130 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 46
2026-05-10 14:11:17.161 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 58
2026-05-10 14:11:17.379 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 51
2026-05-10 14:11:17.399 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 59
2026-05-10 14:11:18.254 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 52
2026-05-10 14:11:18.285 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 60
2026-05-10 14:11:18.401 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 53
2026-05-10 14:11:18.421 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 61
2026-05-10 14:11:18.814 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 54
2026-05-10 14:11:18.843 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 62
2026-05-10 14:11:21.471 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 57
2026-05-10 14:11:21.496 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 63
2026-05-10 14:11:21.608 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 59
2026-05-10 14:11:21.635 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 64
2026-05-10 14:11:22.554 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 62
2026-05-10 14:11:22.599 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 65
2026-05-10 14:11:22.781 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 60
2026-05-10 14:11:22.823 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 66
2026-05-10 14:11:23.139 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 61
2026-05-10 14:11:23.156 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 67
2026-05-10 14:11:23.589 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 55
2026-05-10 14:11:23.625 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 68
2026-05-10 14:11:24.596 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 58
2026-05-10 14:11:24.622 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 69
2026-05-10 14:11:24.990 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 63
2026-05-10 14:11:25.015 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 70
2026-05-10 14:11:25.184 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 56
2026-05-10 14:11:25.219 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 71
2026-05-10 14:11:25.928 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 64
2026-05-10 14:11:25.956 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 72
2026-05-10 14:11:26.837 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 65
2026-05-10 14:11:26.856 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 73
2026-05-10 14:11:27.000 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 66
2026-05-10 14:11:27.021 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 74
2026-05-10 14:11:27.392 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 67
2026-05-10 14:11:27.424 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 75
2026-05-10 14:11:29.291 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 70
2026-05-10 14:11:29.311 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 76
2026-05-10 14:11:30.858 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 72
2026-05-10 14:11:30.881 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 77
2026-05-10 14:11:31.023 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 68
2026-05-10 14:11:31.032 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 71
2026-05-10 14:11:31.053 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 78
2026-05-10 14:11:31.090 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 79
2026-05-10 14:11:31.182 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 69
2026-05-10 14:11:31.202 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 80
2026-05-10 14:11:31.267 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 73
2026-05-10 14:11:31.298 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 81
2026-05-10 14:11:31.822 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 74
2026-05-10 14:11:31.847 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 82
2026-05-10 14:11:31.936 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 75
2026-05-10 14:11:31.950 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 83
2026-05-10 14:11:33.525 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 76
2026-05-10 14:11:33.571 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 84
2026-05-10 14:11:35.192 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 77
2026-05-10 14:11:35.221 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 85
2026-05-10 14:11:35.726 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 81
2026-05-10 14:11:35.753 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 86
2026-05-10 14:11:36.680 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 83
2026-05-10 14:11:36.706 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 87
2026-05-10 14:11:36.736 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 79
2026-05-10 14:11:36.748 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 88
2026-05-10 14:11:36.875 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 82
2026-05-10 14:11:36.883 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 89
2026-05-10 14:11:37.400 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 78
2026-05-10 14:11:37.451 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 90
2026-05-10 14:11:37.832 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 84
2026-05-10 14:11:37.857 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 91
2026-05-10 14:11:37.980 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 80
2026-05-10 14:11:38.004 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 92
2026-05-10 14:11:39.199 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 85
2026-05-10 14:11:39.225 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 93
2026-05-10 14:11:39.917 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 86
2026-05-10 14:11:39.935 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 94
2026-05-10 14:11:40.336 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 87
2026-05-10 14:11:40.353 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 95
2026-05-10 14:11:41.100 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 89
2026-05-10 14:11:41.158 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 96
2026-05-10 14:11:42.436 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 91
2026-05-10 14:11:42.451 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 97
2026-05-10 14:11:43.332 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 93
2026-05-10 14:11:43.376 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 98
2026-05-10 14:11:43.679 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 88
2026-05-10 14:11:43.705 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 99
2026-05-10 14:11:44.051 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 90
2026-05-10 14:11:44.069 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 100
2026-05-10 14:11:44.117 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 92
2026-05-10 14:11:44.134 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 101
2026-05-10 14:11:44.273 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 95
2026-05-10 14:11:44.291 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 102

Polishing not needed - no active set detected at optimal point

2026-05-10 14:13:34.744 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 269
2026-05-10 14:13:34.763 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 277
2026-05-10 14:13:35.224 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 270
2026-05-10 14:13:35.246 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 278
2026-05-10 14:13:35.570 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 271
2026-05-10 14:13:35.583 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 279
2026-05-10 14:13:37.271 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 272
2026-05-10 14:13:37.290 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 280
2026-05-10 14:13:37.764 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 273
2026-05-10 14:13:37.782 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 281
2026-05-10 14:13:38.138 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 274
2026-05-10 14:13:38.156 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 282
2026-05-10 14:13:38.188 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 276
2026-05-10 14:13:38.199 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 283
2026-05-10 14:13:38.425 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 275
2026-05-10 14:13:38.442 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 284
2026-05-10 14:13:40.445 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 277
2026-05-10 14:13:40.475 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 285
2026-05-10 14:13:40.648 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 278
2026-05-10 14:13:40.674 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 286
2026-05-10 14:13:41.008 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 279
2026-05-10 14:13:41.036 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 287
2026-05-10 14:13:42.498 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 284
2026-05-10 14:13:42.514 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 288
2026-05-10 14:13:43.700 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 283
2026-05-10 14:13:43.712 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 280
2026-05-10 14:13:43.720 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 289
2026-05-10 14:13:43.733 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 290
2026-05-10 14:13:43.805 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 282
2026-05-10 14:13:43.819 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 291
2026-05-10 14:13:44.624 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 281
2026-05-10 14:13:44.645 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 292
2026-05-10 14:13:45.941 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 286
2026-05-10 14:13:45.964 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 293
2026-05-10 14:13:46.244 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 287
2026-05-10 14:13:46.263 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 294
2026-05-10 14:13:46.266 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 285
2026-05-10 14:13:46.304 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 295
2026-05-10 14:13:47.231 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 288
2026-05-10 14:13:47.256 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 296
2026-05-10 14:13:48.528 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 290
2026-05-10 14:13:48.545 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 289
2026-05-10 14:13:48.546 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 297
2026-05-10 14:13:48.568 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 298
2026-05-10 14:13:48.925 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 291
2026-05-10 14:13:48.957 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 299
2026-05-10 14:13:49.626 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 292
2026-05-10 14:13:49.647 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 300
2026-05-10 14:13:50.404 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 295
2026-05-10 14:13:50.453 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 301
2026-05-10 14:13:50.730 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 293
2026-05-10 14:13:50.746 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 302
2026-05-10 14:13:50.900 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 294
2026-05-10 14:13:50.912 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 303
2026-05-10 14:13:51.467 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 296
2026-05-10 14:13:51.490 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 304
2026-05-10 14:13:53.355 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 297
2026-05-10 14:13:53.358 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 298
2026-05-10 14:13:53.376 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 305
2026-05-10 14:13:53.378 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 306
2026-05-10 14:13:53.866 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 299
2026-05-10 14:13:53.898 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 307
2026-05-10 14:13:53.947 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 300
2026-05-10 14:13:53.983 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 308
2026-05-10 14:13:54.771 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 303
2026-05-10 14:13:54.788 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 309
2026-05-10 14:13:55.055 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 301
2026-05-10 14:13:55.082 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 310
2026-05-10 14:13:55.434 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 302
2026-05-10 14:13:55.448 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 311
2026-05-10 14:13:55.902 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 304
2026-05-10 14:13:55.920 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 312
2026-05-10 14:13:57.752 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 305
2026-05-10 14:13:57.778 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 313
2026-05-10 14:13:58.290 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 307
2026-05-10 14:13:58.296 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 306
2026-05-10 14:13:58.304 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 314
2026-05-10 14:13:58.309 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 315
2026-05-10 14:13:58.822 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 308
2026-05-10 14:13:58.840 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 316
2026-05-10 14:13:58.932 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 311
2026-05-10 14:13:58.953 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 317
2026-05-10 14:13:59.070 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 309
2026-05-10 14:13:59.080 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 318
2026-05-10 14:13:59.317 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 310
2026-05-10 14:13:59.356 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 319
2026-05-10 14:13:59.619 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 312
2026-05-10 14:13:59.631 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 320
2026-05-10 14:14:02.589 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 313
2026-05-10 14:14:02.620 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 321
2026-05-10 14:14:03.560 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 315
2026-05-10 14:14:03.589 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 322
2026-05-10 14:14:03.653 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 314
2026-05-10 14:14:03.678 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 323
2026-05-10 14:14:03.860 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 320
2026-05-10 14:14:03.876 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 324
2026-05-10 14:14:03.914 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 316
2026-05-10 14:14:03.927 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 325
2026-05-10 14:14:04.133 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 317
2026-05-10 14:14:04.143 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 326
2026-05-10 14:14:04.189 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 318
2026-05-10 14:14:04.232 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 327
2026-05-10 14:14:04.394 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 319
2026-05-10 14:14:04.408 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 328
2026-05-10 14:14:07.137 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 321
2026-05-10 14:14:07.158 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 329
2026-05-10 14:14:08.234 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 328
2026-05-10 14:14:08.264 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 330
2026-05-10 14:14:08.563 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 324
2026-05-10 14:14:08.575 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 331
2026-05-10 14:14:08.585 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 322
2026-05-10 14:14:08.607 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 332
2026-05-10 14:14:08.872 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 327
2026-05-10 14:14:08.883 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 333
2026-05-10 14:14:09.040 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 323
2026-05-10 14:14:09.052 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 334
2026-05-10 14:14:09.145 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 325
2026-05-10 14:14:09.173 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 335
2026-05-10 14:14:09.219 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 326
2026-05-10 14:14:09.239 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 336

Polishing not needed - no active set detected at optimal point

2026-05-10 14:14:11.360 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 329
2026-05-10 14:14:11.375 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 337
2026-05-10 14:14:12.836 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 330
2026-05-10 14:14:12.876 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 338
2026-05-10 14:14:13.197 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 332
2026-05-10 14:14:13.219 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 339
2026-05-10 14:14:13.334 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 331
2026-05-10 14:14:13.369 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 340
2026-05-10 14:14:13.437 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 335
2026-05-10 14:14:13.449 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 341
2026-05-10 14:14:13.629 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 334
2026-05-10 14:14:13.654 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 342
2026-05-10 14:14:13.737 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 333
2026-05-10 14:14:13.764 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 343
2026-05-10 14:14:13.912 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 336
2026-05-10 14:14:13.928 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 344
2026-05-10 14:14:15.940 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 337
2026-05-10 14:14:15.957 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 345
2026-05-10 14:14:17.569 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 339
2026-05-10 14:14:17.593 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 346
2026-05-10 14:14:17.743 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 338
2026-05-10 14:14:17.780 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 347
2026-05-10 14:14:17.918 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 343
2026-05-10 14:14:17.951 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 348
2026-05-10 14:14:18.109 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 340
2026-05-10 14:14:18.119 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 349
2026-05-10 14:14:18.136 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 341
2026-05-10 14:14:18.162 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 350
2026-05-10 14:14:18.296 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 342
2026-05-10 14:14:18.316 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 351
2026-05-10 14:14:18.674 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 344
2026-05-10 14:14:18.688 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 352
2026-05-10 14:14:20.475 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 345
2026-05-10 14:14:20.505 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 353
2026-05-10 14:14:22.208 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 346
2026-05-10 14:14:22.230 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 354
2026-05-10 14:14:22.396 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 347
2026-05-10 14:14:22.432 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 355
2026-05-10 14:14:22.549 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 348
2026-05-10 14:14:22.567 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 356
2026-05-10 14:14:22.633 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 351
2026-05-10 14:14:22.637 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 349
2026-05-10 14:14:22.644 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 357
2026-05-10 14:14:22.674 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 358
2026-05-10 14:14:22.794 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 350
2026-05-10 14:14:22.822 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 359
2026-05-10 14:14:23.319 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 352
2026-05-10 14:14:23.341 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 360
2026-05-10 14:14:25.126 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 353
2026-05-10 14:14:25.147 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 361
2026-05-10 14:14:26.598 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 359
2026-05-10 14:14:26.618 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 362
2026-05-10 14:14:27.119 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 354
2026-05-10 14:14:27.133 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 363
2026-05-10 14:14:27.189 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 355
2026-05-10 14:14:27.199 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 364
2026-05-10 14:14:27.207 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 357
2026-05-10 14:14:27.222 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 365
2026-05-10 14:14:27.310 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 356
2026-05-10 14:14:27.317 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 366
2026-05-10 14:14:27.365 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 358
2026-05-10 14:14:27.379 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 367
2026-05-10 14:14:28.270 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 360
2026-05-10 14:14:28.289 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 368
2026-05-10 14:14:30.068 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 361
2026-05-10 14:14:30.100 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 369
2026-05-10 14:14:30.584 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 362
2026-05-10 14:14:30.600 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 370
2026-05-10 14:14:30.697 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 367
2026-05-10 14:14:30.711 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 371
2026-05-10 14:14:31.317 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 365
2026-05-10 14:14:31.333 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 372
2026-05-10 14:14:31.419 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 364
2026-05-10 14:14:31.427 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 373
2026-05-10 14:14:31.638 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 363
2026-05-10 14:14:31.655 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 374
2026-05-10 14:14:31.904 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 366
2026-05-10 14:14:31.926 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 375
2026-05-10 14:14:32.989 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 368
2026-05-10 14:14:33.009 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 376
2026-05-10 14:14:35.094 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 372
2026-05-10 14:14:35.110 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 377
2026-05-10 14:14:35.179 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 371
2026-05-10 14:14:35.199 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 378
2026-05-10 14:14:35.246 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 370
2026-05-10 14:14:35.256 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 379
2026-05-10 14:14:35.332 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 369
2026-05-10 14:14:35.354 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 380
2026-05-10 14:14:35.404 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 375
2026-05-10 14:14:35.416 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 381
2026-05-10 14:14:35.484 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 373
2026-05-10 14:14:35.522 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 382
2026-05-10 14:14:36.132 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 374
2026-05-10 14:14:36.158 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:282 - Deconvolute fractions for bulk: 383
2026-05-10 14:14:38.537 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 376
2026-05-10 14:14:38.924 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 382
2026-05-10 14:14:39.245 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 378
2026-05-10 14:14:39.342 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 383
2026-05-10 14:14:39.447 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 381
2026-05-10 14:14:39.466 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 380
2026-05-10 14:14:39.628 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 379
2026-05-10 14:14:39.733 | INFO     | rectanglepy.tl.deconvolution:_process_bulk:285 - Finished deconvolution for bulk: 377

## View results

In [8]:
estimations.iloc[:5, :5]

,choroid plexus,diencephalon lin.,dorsal forebrain,dorsal forebrain prog.,eye
1-H1-dorsal-day013-016,0.000000e+00,0.004489,0.000000e+00,0.000000e+00,0.094482
1-H9-dorsal-day013-016,6.700154e-02,0.047729,5.054615e-04,1.472069e-01,0.001300
1-ROZH_5-dorsal-day013-016,4.401197e-02,0.000000,1.289160e-09,1.263389e-01,0.000000
1-XUJA_2-dorsal-day013-016,9.923372e-11,0.021819,0.000000e+00,1.569445e-10,0.061339
1-176-dorsal-day013-016,5.563749e-04,0.055441,1.752628e-10,5.456333e-10,0.000000

## Save outputs

In [ ]:
# Save the estimations
estimations.to_csv("braino_rectangle_estimations.csv")

# Save the error by genes
signature_result.unkn_bulk_err.to_csv("braino_rectangle_err.csv")

## Day013 top 10 unknown-error genes per protocol/cell line

In [4]:
err = pd.read_csv("braino_rectangle_err.csv", index_col=0)

# Parse sample IDs: replicate-cell_line-protocol-day-...
sample_meta = err.index.to_series().str.split("-", expand=True)

sample_meta = sample_meta.iloc[:, :4].copy()
sample_meta.columns = ["replicate", "cell_line", "protocol", "day"]

# Keep first time point only (day013)
day013_mask = sample_meta["day"] == "day013"
err_day013 = err.loc[day013_mask].copy()
meta_day013 = sample_meta.loc[day013_mask, ["protocol", "cell_line"]].copy()

# Mean error per gene across replicates for each protocol and cell line
err_mean = (
    err_day013
    .assign(
        protocol=meta_day013["protocol"].values,
        cell_line=meta_day013["cell_line"].values,
    )
    .groupby(["protocol", "cell_line"], as_index=True)
    .mean(numeric_only=True)
)

# Extract top 10 genes with highest mean error in each group
top10_tables = []
for (protocol, cell_line), row in err_mean.iterrows():
    top10 = row.nlargest(10).rename("mean_error").reset_index()
    top10.columns = ["gene", "mean_error"]
    top10.insert(0, "cell_line", cell_line)
    top10.insert(0, "protocol", protocol)
    top10.insert(2, "rank", range(1, len(top10) + 1))
    top10_tables.append(top10)

braino_day013_top10_err = pd.concat(top10_tables, ignore_index=True)
braino_day013_top10_err = braino_day013_top10_err.sort_values(["protocol", "cell_line", "rank"])

out_file = "braino_day013_top10_mean_error_by_protocol_cellline.csv"
braino_day013_top10_err.to_csv(out_file, index=False)

print(f"Saved: {out_file}")
braino_day013_top10_err

Saved: braino_day013_top10_mean_error_by_protocol_cellline.csv

    protocol cell_line  rank    gene   mean_error
0     dorsal       176     1  TUBA1B  2886.834771
1     dorsal       176     2    TUBB  2002.063205
2     dorsal       176     3   RPS29  1781.606917
3     dorsal       176     4  TUBB2B  1329.742018
4     dorsal       176     5   SOX11  1311.580659
..       ...       ...   ...     ...          ...
275  ventral    XUJA_2     6   NR2F2  1197.665196
276  ventral    XUJA_2     7   RPS29  1164.577319
277  ventral    XUJA_2     8  NAP1L1  1156.453668
278  ventral    XUJA_2     9  HNRNPU  1101.626861
279  ventral    XUJA_2    10    FZD3  1075.031886

[280 rows x 5 columns]